# Site settings
title: "NHS Hack Day"
name: "NHS Hack Day"
email: hello@openhealthcare.org.uk
description: > # this means to ignore newlines until "baseurl:"
  Helping make NHS IT less bad. Promoting good health, good practice and good science.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.nhshackday.com" # the base hostname & protocol for your site
twitter_username: NHSHackDay
markdown: kramdown
sass:
  sourceMap: true
  style: compressed
  sass_dir: _sass
github_repository_url: https://github.com/nhshackday/nhshackday.github.io